version: '3.8'

services:
  # WPH Hotel Booking System API
  wph-hotel-api:
    build:
      context: .
      dockerfile: WPHBookingSystem.WebUI/Dockerfile
    container_name: wph-hotel-api
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:6000
      - ConnectionStrings__DefaultConnection=Host=ep-rough-brook-a15a4fjt-pooler.ap-southeast-1.aws.neon.tech;Database=wph-hotel;Username=neondb_owner;Password=npg_uKp9a4Wdvegn;Ssl Mode=Require;Trust Server Certificate=true
      - JwtSettings__Key=your-super-secret-key-with-at-least-256-bits-32-characters-long
      - JwtSettings__Issuer=WPHHotelAPI
      - JwtSettings__Audience=WPHHotelClient
      - JwtSettings__ExpirationHours=24
      - ImageSettings__UploadPath=wwwroot/images/rooms
      - ImageSettings__BaseUrl=/images/rooms
      - ImageSettings__MaxFileSize=52428800
    volumes:
      - wph-hotel-images:/app/wwwroot/images
    networks:
      - wph-hotel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wph-hotel-images:
    driver: local

networks:
  wph-hotel-network:
    driver: bridge 