version: '3.8'

services:
  # WPH Hotel Booking System API
  wph-hotel-api:
    build:
      context: .
      dockerfile: WPHBookingSystem.WebUI/Dockerfile
    container_name: wph-hotel-api
    ports:
      - "5069:5069"
    environment:
      # Application Settings
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5069
      - AllowedHosts=*
      
      # Database Connection
      - ConnectionStrings__DefaultConnection=Host=ep-rough-brook-a15a4fjt-pooler.ap-southeast-1.aws.neon.tech;Database=wph-hotel;Username=neondb_owner;Password=npg_uKp9a4Wdvegn;Ssl Mode=Require;Trust Server Certificate=true
      
      # JWT Authentication
      - JwtSettings__Key=your-super-secret-key-with-at-least-256-bits-32-characters-long
      - JwtSettings__Issuer=WPHHotelAPI
      - JwtSettings__Audience=WPHHotelClient
      - JwtSettings__ExpirationHours=24
      
      # Image Upload Settings
      - ImageSettings__UploadPath=wwwroot/images/rooms
      - ImageSettings__BaseUrl=/images/rooms
      - ImageSettings__MaxFileSize=5242880
      - ImageSettings__AllowedExtensions__0=.jpg
      - ImageSettings__AllowedExtensions__1=.jpeg
      - ImageSettings__AllowedExtensions__2=.png
      - ImageSettings__AllowedExtensions__3=.gif
      - ImageSettings__AllowedExtensions__4=.webp
      
      # Email Settings (MailKit)
      - EmailSettings__SmtpHost=mail.venvi.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__FromEmail=administrator@venvi.com
      - EmailSettings__FromName=WPH Hotel
      - EmailSettings__Username=administrator@venvi.com
      - EmailSettings__Password=newmis2021
      - EmailSettings__EnableSsl=true
      - EmailSettings__EnableAuthentication=true
      - EmailSettings__BaseUrl=https://wph-hotel.gregdoesdev.xyz
      
      # Hotel Information for Emails
      - EmailSettings__HotelInfo__Name=WPH Hotel
      - EmailSettings__HotelInfo__Address=123 Hotel Street, City, Country
      - EmailSettings__HotelInfo__Phone=+1 (555) 123-4567
      - EmailSettings__HotelInfo__Email=info@wphhotel.com
      - EmailSettings__HotelInfo__Website=https://wph-hotel.gregdoesdev.xyz
      - EmailSettings__HotelInfo__LogoUrl=https://wph-hotel.gregdoesdev.xyz/ChatGPT%20Image%20Jun%204,%202025,%2002_33_57%20PM.png
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - Logging__LogLevel__WPHBookingSystem.WebUI=Debug
      - Logging__LogLevel__Microsoft.AspNetCore.Routing=Debug
      - Logging__LogLevel__Microsoft.AspNetCore.Cors=Information
      - Logging__LogLevel__Microsoft.AspNetCore.Authentication=Information
      - Logging__LogLevel__WPHBookingSystem.Infrastructure.Services.EmailService=Information
      
      # CORS Settings (for production)
      - CorsSettings__AllowedOrigins=https://wph-hotel.gregdoesdev.xyz,http://localhost:3000,http://localhost:3001
      
      # Request Limits
      - RequestLimits__MaxRequestBodySize=52428800
      - RequestLimits__MultipartBodyLengthLimit=52428800
    volumes:
      - wph-hotel-images:/app/wwwroot/images
    networks:
      - wph-hotel-network
    restart: unless-stopped

volumes:
  wph-hotel-images:
    driver: local

networks:
  wph-hotel-network:
    driver: bridge 