version: '3.8'

services:
  # WPH Hotel Booking System API
  wph-hotel-api:
    build:
      context: .
      dockerfile: WPHBookingSystem.WebUI/Dockerfile
    container_name: wph-hotel-api
    ports:
      - "5069:5069"
    environment:
      # Application Settings
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5069
      
      # Database Connection - UPDATE WITH YOUR ACTUAL VALUES
      - ConnectionStrings__DefaultConnection=Host=your-neon-host;Database=your-database;Username=your-username;Password=your-password;Ssl Mode=Require;Trust Server Certificate=true
      
      # JWT Authentication - UPDATE WITH YOUR ACTUAL VALUES
      - JwtSettings__Key=your-super-secret-key-with-at-least-256-bits-32-characters-long
      - JwtSettings__Issuer=WPHHotelAPI
      - JwtSettings__Audience=WPHHotelClient
      - JwtSettings__ExpirationHours=24
      
      # Image Upload Settings
      - ImageSettings__UploadPath=wwwroot/images/rooms
      - ImageSettings__BaseUrl=/images/rooms
      - ImageSettings__MaxFileSize=52428800
      
      # Email Settings (MailKit) - UPDATE WITH YOUR ACTUAL VALUES
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__FromEmail=your-email@yourdomain.com
      - EmailSettings__FromName=WPH Hotel
      - EmailSettings__Username=your-email@gmail.com
      - EmailSettings__Password=your-app-password
      - EmailSettings__EnableSsl=true
      - EmailSettings__EnableAuthentication=true
      - EmailSettings__BaseUrl=https://your-frontend-domain.com
      
      # Hotel Information for Emails - UPDATE WITH YOUR ACTUAL VALUES
      - EmailSettings__HotelInfo__Name=WPH Hotel
      - EmailSettings__HotelInfo__Address=Your Hotel Address
      - EmailSettings__HotelInfo__Phone=Your Hotel Phone
      - EmailSettings__HotelInfo__Email=info@yourdomain.com
      - EmailSettings__HotelInfo__Website=https://yourdomain.com
      - EmailSettings__HotelInfo__LogoUrl=https://yourdomain.com/images/logo.png
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__Microsoft.AspNetCore.Cors=Information
      - Logging__LogLevel__Microsoft.AspNetCore.Authentication=Information
      - Logging__LogLevel__WPHBookingSystem.Infrastructure.Services.EmailService=Information
      
      # CORS Settings - UPDATE WITH YOUR ACTUAL FRONTEND DOMAINS
      - CorsSettings__AllowedOrigins=https://your-frontend-domain.com,https://www.your-frontend-domain.com
      
      # Request Limits
      - RequestLimits__MaxRequestBodySize=52428800
      - RequestLimits__MultipartBodyLengthLimit=52428800
    volumes:
      - wph-hotel-images:/app/wwwroot/images
    networks:
      - wph-hotel-network
    restart: unless-stopped

volumes:
  wph-hotel-images:
    driver: local

networks:
  wph-hotel-network:
    driver: bridge 