using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WPHBookingSystem.Application.Interfaces;
using WPHBookingSystem.Domain.Entities;
using WPHBookingSystem.Infrastructure.Persistence.Data;

namespace WPHBookingSystem.Infrastructure.Repositories
{
    /// <summary>
    /// Specialized repository for booking-related data access operations.
    /// Extends GenericRepository to provide booking-specific query methods and business logic.
    /// 
    /// This repository handles complex booking queries including email-based lookups,
    /// occupancy calculations, and revenue analysis.
    /// </summary>
    public class BookingRepository(ApplicationDbContext context) : GenericRepository<Booking>(context), IBookingRepository
    {
        private readonly ApplicationDbContext _context = context;

        /// <summary>
        /// Retrieves all bookings for a specific room, ordered by check-in date.
        /// Includes room information for complete booking details.
        /// </summary>
        /// <param name="roomId">The unique identifier of the room.</param>
        /// <returns>A list of bookings for the specified room.</returns>
        public async Task<List<Booking>> GetBookingsByRoomIdAsync(Guid roomId)
        {
            return await _context.Bookings
                .Include(b => b.Room)
                .Where(b => b.RoomId == roomId)
                .OrderByDescending(b => b.CheckIn)
                .ToListAsync();
        }

        /// <summary>
        /// Retrieves all bookings for a specific email address, ordered by check-in date.
        /// Provides user-centric view of booking history.
        /// </summary>
        /// <param name="emailAddress">The email address to search for bookings.</param>
        /// <returns>A list of bookings for the specified email address.</returns>
        public async Task<List<Booking>> GetBookingsByEmailAsync(string emailAddress)
        {
            return await _context.Bookings
                .Include(b => b.Room)
                .Where(b => b.EmailAddress.ToLower() == emailAddress.ToLower())
                .OrderByDescending(b => b.CheckIn)
                .ToListAsync();
        }

        /// <summary>
        /// Calculates the occupancy rate for a room during the specified date range.
        /// Provides business intelligence for room utilization analysis.
        /// </summary>
        /// <param name="roomId">The unique identifier of the room.</param>
        /// <param name="start">The start date for occupancy calculation.</param>
        /// <param name="end">The end date for occupancy calculation.</param>
        /// <returns>The occupancy rate as a percentage (0-100).</returns>
        public async Task<int> GetOccupancyRateAsync(Guid roomId, DateTime start, DateTime end)
        {
            var totalDays = (end - start).TotalDays;
            if (totalDays <= 0)
                return 0;

            var bookings = await _context.Bookings
                .Where(b => b.RoomId == roomId &&
                           ((b.CheckIn >= start && b.CheckIn < end) ||
                            (b.CheckOut > start && b.CheckOut <= end) ||
                            (b.CheckIn <= start && b.CheckOut >= end)))
                .ToListAsync();

            var occupiedDays = bookings.Sum(b =>
            {
                var bookingStart = b.CheckIn > start ? b.CheckIn : start;
                var bookingEnd = b.CheckOut < end ? b.CheckOut : end;
                return (bookingEnd - bookingStart).TotalDays;
            });

            return (int)((occupiedDays / totalDays) * 100);
        }

        /// <summary>
        /// Calculates the total revenue generated by a room during the specified date range.
        /// Provides financial reporting capabilities for business analysis.
        /// </summary>
        /// <param name="roomId">The unique identifier of the room.</param>
        /// <param name="start">Optional start date for revenue calculation.</param>
        /// <param name="end">Optional end date for revenue calculation.</param>
        /// <returns>The total revenue amount for the specified period.</returns>
        public async Task<decimal> GetTotalRevenueAsync(Guid roomId, DateTime? start = null, DateTime? end = null)
        {
            var query = _context.Bookings.Where(b => b.RoomId == roomId);

            if (start.HasValue)
                query = query.Where(b => b.CheckIn >= start.Value);

            if (end.HasValue)
                query = query.Where(b => b.CheckOut <= end.Value);

            return await query.SumAsync(b => b.TotalAmount);
        }

        /// <summary>
        /// Retrieves all bookings with room information included.
        /// Provides complete booking data with associated room details for administrative purposes.
        /// </summary>
        /// <returns>A list of all bookings with room information.</returns>
        public async Task<List<Booking>> GetAllBookingsWithRoomAsync()
        {
            return await _context.Bookings
                .Include(b => b.Room)
                .OrderByDescending(b => b.CheckIn)
                .ToListAsync();
        }
    }
}
